### ISSUE TITLE
Navbar size increases on hover

### ISSUE THREAD

**Issue by halworsen** [Programvareverkstedet/nettsiden#4]
Only happens when you're on a page which doesn't highlight any of the navbar elements as active (e.g. the admin pages). Slightly annoying.

**Comment by pbsds** [comment]
Hmm, we could decrease the height of the navbar buttons by the border-bottom width, or give the navbar buttons a default border-bottom with the same color as the background. Preferably both

**Comment by halworsen** [comment]
Seems to have been fixed
